Document: gpsrecord
Title: Debian gpsrecord Manual
Author: <insert document author here>
Abstract: This manual describes what gpsrecord is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gpsrecord/gpsrecord.sgml.gz

Format: postscript
Files: /usr/share/doc/gpsrecord/gpsrecord.ps.gz

Format: text
Files: /usr/share/doc/gpsrecord/gpsrecord.text.gz

Format: HTML
Index: /usr/share/doc/gpsrecord/html/index.html
Files: /usr/share/doc/gpsrecord/html/*.html


