#!/bin/sh
# postinst script for ecoach
#
# see: dh_installdeb(1)

set -e

gtk-update-icon-cache -f /usr/share/icons/hicolor
#maemo-select-menu-location gpsrecorder.desktop

# replaced 'exit 0' by this so the maemo-optify script can append some code
# safely :)
echo > /dev/null
